SecondHalfGames/yakui

- CHANGELOG.md
- crates/yakui-wgpu/src/lib.rs
* Add `yakui_wgpu::State::paint_with_encoder()` for encoding render commands to an existing `&mut wgpu::CommandEncoder`.
* Add yakui to the render pass label
> Add yakui_wgpu::State::paint_with_encoder()

- crates/yakui-widgets/src/widgets/render_text.rs
This helps text be less blurry, though the positioning may be off if the rest of the layout has fractional positions.
> Round text positions to the nearest pixel

- crates/yakui-core/src/paint/texture.rs
- crates/yakui-test/src/lib.rs
changes the debug on `Texture` to be a little easier to read. Since there *is* a `data` function, it seems like users should be able to log out the texture data if needed
> Do not debug a vec of texture data

- crates/yakui-core/src/geometry/rect.rs
- crates/yakui-core/src/input/input_state.rs
- crates/yakui-core/src/layout/mod.rs
- crates/yakui-core/src/paint/paint_dom.rs
- crates/yakui-widgets/src/widgets/render_textbox.rs
- crates/yakui-widgets/src/widgets/scrollable.rs
Fixes #61.
This PR reworks yakui's clipping API to happen during layout instead of just during paint. This lets us use it during hit testing and will also let us perform paint culling.
> Clipping v2

- crates/yakui-core/src/input/mod.rs
- crates/yakui-core/src/input/navigation.rs
- crates/yakui-core/src/widget.rs
Closes #7.
This is an early WIP. Navigation is done via a new widget method that lets widgets specify their connections: left, right, up, down, previous, and next.
Need to figure out how to bubble this information (should it be an event instead?) and how to render selection halos that reduces the burden of individual widgets.
We may want to decouple selection and focus, especially for things like sliders on controllers.
> Gamepad and Keyboard Navigation

- crates/yakui-core/src/input/input_state.rs
- crates/yakui-core/tests/regression.rs
Fixes #38.
This change makes the input handling code much more robust when poking at the DOM with IDs.
> Fix panicking in input handling code

- crates/yakui-vulkan/src/lib.rs
- crates/yakui-vulkan/src/util.rs
- Previously, the Vulkan Renderer test was not setting `unscaled_viewport_size` correctly. This has been fixed!
- Render surfaces can now have their `LOAD_OP` configured, allowing alpha blending on top of the underlying window, for example when rendering some UI in a game.
- Alpha blending has been configured in the renderpass to enable this
> Fix some small bugs with the Vulkan renderer

- crates/yakui-widgets/src/widgets/textbox.rs
- crates/yakui/examples/textbox.rs
Bikeshedding welcome on the field name; I'm not really in love with `activated`, but I couldn't find a good precedent in web APIs.
> Expose whether Enter was hit in a TextBox

- crates/yakui-widgets/src/text_renderer.rs
The row height was never summed to itself so from the third row
onwards would appear in the same height as the second row
The code is therefore simplied to always track the `max_height`
attained by any given glyph which results in the correct behavior
Fixes https://github.com/SecondHalfGames/yakui/issues/112
Tested with
```rust
for i in 0..100 {
text(100.0 - i as f32, "the fox jumped over the lazy dog");
}
```
in renderdoc
Before:
After:
> Fix text renderer

- crates/yakui-widgets/src/shapes.rs
This allows reusing the rounded rect everywhere a component can have rounded drawing needs without needed to special case the zero radius case (button region, box, ...) as well as handling pathological cases a bit nicer.
I think we could also merge `colored_box` with `round_rect` by simply having `colored_box` provide a `border_radius` parameter (we can keep the shorthand though)
> RoundedRect bails out to rect if radius is zero

- crates/bootstrap/Cargo.toml
- crates/demo/Cargo.toml
- crates/yakui-app/Cargo.toml
- crates/yakui-app/src/lib.rs
- crates/yakui-to-image/Cargo.toml
- crates/yakui-to-image/src/graphics.rs
- crates/yakui-wgpu/Cargo.toml
I chose not to do anything fancy with the surface and keep the same unsafe as before. Arcanisation of the window could be done in a separate PR since this is just for the demo, so that we can use yakui with wgpu 0.19
> Update to wgpu 0.19

- crates/yakui-core/src/types.rs
- crates/yakui-widgets/src/widgets/list.rs
- crates/yakui/examples/main_alignment.rs
Add the Space* alignments using the same algorithm as Flutter:
https://github.com/flutter/flutter/blob/67457e669f/packages/flutter/lib/src/rendering/flex.dart#L963
(which is also the CSS spec, the Flutter doc is really vague about the details).
> add more main axis alignments

- crates/yakui-widgets/src/shapes.rs
- crates/yakui-widgets/src/widgets/cutout.rs
- crates/yakui/examples/blur.rs
Also fixes "color" not being passed to `PaintRect` when using fallback and optimize allocations a bit
Also means RoundedRectangle now supports images so that can be used elsewhere
> allow cutout to be rounded

- crates/bootstrap/src/lib.rs
- crates/yakui-wgpu/src/lib.rs
- crates/yakui-wgpu/src/samplers.rs
- crates/yakui-wgpu/src/texture.rs
The user can provide custom textures that have been properly mipmapped.
So we allow nice trilinear filtering
> yakui-wgpu: add mipmap filtering for custom textures

- crates/yakui-core/src/types.rs
- crates/yakui-widgets/src/shorthand.rs
- crates/yakui-widgets/src/widgets/reflow.rs
- crates/yakui-widgets/tests/snapshot.rs
- crates/yakui/examples/dropdown.rs
This allows reflowing while taking into account the child size. I personally need this to be able to show a tooltip over a button (when hovered for a bit) that is nicely centered.
I introduced a new "Pivot" type to avoid accidentally swapping the anchor and the pivot arguments in the `reflow` shorthand.
Another idea: This could be implemented as a separate `Pivot` widget with the same offset logic.
Could also be added to the `Offset` widget which would now also take relative (pivot) coordinates.
(Could be worth simplifying `Flow::Relative` removing offset since the Offset widget can already do this?)
Some screenshots:
Backward compat: Pivot is `TOP_LEFT`.
Pivot is 'CENTER':
Pivot is equal to anchor:
> Add pivot to reflow

- crates/yakui-core/Cargo.toml
- crates/yakui-core/src/event.rs
- crates/yakui-core/src/geometry/color.rs
- crates/yakui-wgpu/Cargo.toml
- Update to bitflags 2 (need to derive by hand, bits -> bits())
- keyboards-types also updates bitflags to v2
- Remove palette in favor of `fast-srgb` (which palette used under the hood)
Compile time improvements from quick testing:
```bash
cargo clean && cargo build -p yakui
Before: ~6.2s
After:  ~3.4s
```
<details>
<summary> old tree </summary>
```
> cargo tree -p yakui -e normal
yakui v0.2.0 (/home/pdouady/repos/yakui/crates/yakui)
├── yakui-core v0.2.0 (/home/pdouady/repos/yakui/crates/yakui-core)
│   ├── anymap v0.12.1
│   ├── bitflags v1.3.2
│   ├── glam v0.24.2
│   ├── keyboard-types v0.6.2
│   │   └── bitflags v1.3.2
│   ├── log v0.4.20
│   ├── palette v0.7.4
│   │   ├── approx v0.5.1
│   │   │   └── num-traits v0.2.17
│   │   ├── fast-srgb8 v1.0.0
│   │   ├── palette_derive …
```
> Update dependencies and remove palette (2x improvement in compile time)

- crates/yakui-vulkan/src/lib.rs
If an application has a rendering pass with multiple subpasses, the UI should ideally be able to be rendered on top of the last subpass to avoid being negatively affected by future subpasses. This PR adds that option to `yakui_vulkan::Options`.
> Support rendering to a different subpass in yakui-vulkan

- crates/yakui-vulkan/src/lib.rs
The `TextureChange::Removed` and `TextureChange::Modified` match arms in `YakuiVulkan::update_textures` both have logic to remove a texture, but the logic is inconsistent between the two arms. This PR changes the `TextureChange::Modified` branch to be consistent with `TextureChange::Removed`.
This change also fixes a crash I experienced when trying to change UI text based on in-game information on a game that has a graphics pipeline depth (simultaneous frames in flight) of 2. The following Vulkan validation error appeared during this crash:
`Validation Error: [ VUID-vkDestroyImage-image-01000 ] | MessageID = 0xf2d29b5a | vkDestroyImage():  can't be called on VkImage 0xe3343f000000028f[] that is currently in use by VkCommandBuffer 0x20919128700[frame]. The Vulkan spec states: All submitted …
> Fix Vulkan crash with TextureChange::Modified

- crates/yakui-vulkan/examples/demo.rs
- crates/yakui-vulkan/src/vulkan_texture.rs
Some small Vulkan fixes.
- Closes #162 
- Closes #163
> Use clamp to edge on vulkan and enable portability features

- crates/yakui-vulkan/examples/demo.rs
- crates/yakui-vulkan/src/descriptors.rs
Sets various `UPDATE_AFTER_BIND_POOL_BIT` flags on descriptors to allow reasonable amounts of image samplers in our descriptor sets on platforms like macOS.
Closes #160
> Fix validation warnings on macOS

- crates/yakui-widgets/src/widgets/textbox.rs
Set the textbox cursor to be within the range of the text in `TextBoxWidget::update`.
Should fix #168
> Put TextBox cursor back in bounds if the text changes (#168)

- crates/yakui-vulkan/src/vulkan_texture.rs
> Use `vk::Format::R8G8B8A8_SRGB` for srgb textures in vulkan

- crates/bootstrap/src/lib.rs
- crates/yakui-core/src/paint/texture.rs
- crates/yakui-vulkan/examples/demo.rs
- crates/yakui-vulkan/src/vulkan_texture.rs
- crates/yakui-wgpu/src/lib.rs
- crates/yakui-wgpu/src/samplers.rs
- crates/yakui-wgpu/src/texture.rs
Addresses #175 
Adds
```rust
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AddressMode {
/// Clamp to the edge of the texture
ClampToEdge,
/// Repeat the texture
Repeat,
}
```
and adds it to
```rust
pub struct Texture {
// [...]
/// How to handle texture addressing
pub address_mode: AddressMode,
}
```
and implements setting the address mode in `yakui-wgpu` and `yakui-vulkan`
> Support setting address modes for yakui textures

- crates/yakui-widgets/src/widgets/render_text.rs
This PR simply adds a panic when a font is missing. This obviously would be a breaking change for some users who might rely on the current behavior.
I'm not sure that `panic` is the correct decision here, but the API really doesn't allow for anything besides that, or the current behavior here. I am making this PR because I believe that panicking is superior given only those two options.
I am open to this PR being rejected without too much complaining -- I understand there might be a difference in direction here
> panic when missing font

- crates/yakui-wgpu/src/bindgroup_cache.rs
- crates/yakui-wgpu/src/lib.rs
avoid recreating them every frame
closes #97
> Add bindgroup cache in wgpu

- crates/yakui-widgets/src/text_renderer.rs
Previously, the text rendering code would make the atlas as big as the GPU allowed. On modern cards this is 32k x 32k, so 4 bytes + 1 byte of mask atlas would end up at 5gb of texture data
> Limit text atlas to 4096^2

- crates/yakui-core/src/context.rs
- crates/yakui-core/src/state.rs
Here comes another niche use case!
Something I've found really useful for iterating on yakui UIs is hot-reloading. Compiling all the yakui code in a separate crate and loading it as a DLL during development provides for a really great development experience.
However, this does rely on exposing some of yakui's internals, which feels a little gross. The function executed in the DLL must do something like the following in order to make sure that the DOM is available at the time any yakui-related code is invoked:
```rust
pub fn gui(dom: &yakui::dom::Dom, state: EditorState, _registry: &ComponentRegistry) {
yakui::context::bind_dom(dom);
gui_inner(state);
yakui::context::unbind_dom();
}
```
(you can find a more complex example in an application that uses this system in anger …
> Expose `bind_dom` and `unbind_dom` for hot reloading
